name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible to help us resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened instead?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: MediaMate Version
      description: What version of MediaMate are you running?
      placeholder: "v0.1.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running MediaMate on?
      options:
        - Linux (amd64)
        - Linux (arm64 / Raspberry Pi)
        - macOS
        - Windows
        - Docker
        - Other
    validations:
      required: true

  - type: dropdown
    id: go-version
    attributes:
      label: Go Version (if building from source)
      options:
        - "1.22"
        - "1.23"
        - "N/A (using Docker)"
        - Other
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant parts of your config (remove sensitive data!)
      placeholder: |
        ```yaml
        llm:
          provider: claude
        backends:
          radarr:
            enabled: true
        ```
      render: yaml
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output
      placeholder: Paste logs here (remove sensitive data!)
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, related issues, workarounds, etc.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have removed any sensitive information from logs and config
          required: true
