package stack

import "strings"

// RenderMediaMateConfig produces a mediamate.yaml configuration file content
// compatible with the internal/config package. It uses Docker service names as
// hostnames since all services run on the same Docker network.
func RenderMediaMateConfig(cfg *Config) string {
	var b strings.Builder

	renderConfigHeader(&b)
	renderConfigArrs(&b, cfg)
	renderConfigTorrentClient(&b, cfg)
	renderConfigMediaServer(&b, cfg)
	renderConfigFooter(&b)

	return b.String()
}

// renderConfigHeader writes the file header, LLM, and TMDb sections.
func renderConfigHeader(b *strings.Builder) {
	b.WriteString("# MediaMate Configuration\n")
	b.WriteString("# Generated by: mediamate stack init\n")
	b.WriteString("# API keys are loaded from environment variables (see .env)\n\n")

	b.WriteString("llm:\n")
	b.WriteString("  provider: \"claude\"\n")
	b.WriteString("  api_key: ${MEDIAMATE_LLM_API_KEY}\n\n")

	b.WriteString("tmdb:\n")
	b.WriteString("  api_key: ${MEDIAMATE_TMDB_API_KEY}\n\n")
}

// renderConfigArrs writes the Radarr, Sonarr, and Readarr sections.
func renderConfigArrs(b *strings.Builder, cfg *Config) {
	if cfg.HasComponent(ComponentRadarr) {
		b.WriteString("radarr:\n")
		b.WriteString("  url: \"http://radarr:7878\"\n")
		b.WriteString("  api_key: ${MEDIAMATE_RADARR_API_KEY}\n")
		b.WriteString("  quality_profile: \"HD-1080p\"\n")
		b.WriteString("  root_folder: \"/movies\"\n\n")
	}

	if cfg.HasComponent(ComponentSonarr) {
		b.WriteString("sonarr:\n")
		b.WriteString("  url: \"http://sonarr:8989\"\n")
		b.WriteString("  api_key: ${MEDIAMATE_SONARR_API_KEY}\n")
		b.WriteString("  quality_profile: \"HD-1080p\"\n")
		b.WriteString("  root_folder: \"/tv\"\n\n")
	}

	if cfg.HasComponent(ComponentReadarr) {
		b.WriteString("readarr:\n")
		b.WriteString("  url: \"http://readarr:8787\"\n")
		b.WriteString("  api_key: ${MEDIAMATE_READARR_API_KEY}\n")
		b.WriteString("  quality_profile: \"Standard\"\n")
		b.WriteString("  root_folder: \"/books\"\n\n")
	}
}

// torrentHost returns the host for a torrent client, using gluetun if present.
func torrentHost(cfg *Config, defaultHost string) string {
	if cfg.HasComponent(ComponentGluetun) {
		return ComponentGluetun
	}
	return defaultHost
}

// renderConfigTorrentClient writes the torrent client section.
func renderConfigTorrentClient(b *strings.Builder, cfg *Config) {
	switch cfg.TorrentClient {
	case ComponentQBittorrent:
		host := torrentHost(cfg, "qbittorrent")
		b.WriteString("qbittorrent:\n")
		b.WriteString("  url: \"http://" + host + ":8080\"\n")
		b.WriteString("  username: \"admin\"\n")
		b.WriteString("  password: ${QBITTORRENT_PASSWORD}\n\n")
	case ComponentTransmission:
		host := torrentHost(cfg, "transmission")
		b.WriteString("# Transmission support requires implementation\n")
		b.WriteString("# transmission:\n")
		b.WriteString("#   url: \"http://" + host + ":9091\"\n")
		b.WriteString("#   username: \"admin\"\n")
		b.WriteString("#   password: ${TRANSMISSION_PASSWORD}\n\n")
	case ComponentDeluge:
		host := torrentHost(cfg, "deluge")
		b.WriteString("# Deluge support requires implementation\n")
		b.WriteString("# deluge:\n")
		b.WriteString("#   url: \"http://" + host + ":8112\"\n")
		b.WriteString("#   password: ${DELUGE_PASSWORD}\n\n")
	}
}

// renderConfigMediaServer writes the media server section.
func renderConfigMediaServer(b *strings.Builder, cfg *Config) {
	switch cfg.MediaServer {
	case ComponentJellyfin:
		if cfg.HasComponent(ComponentJellyfin) {
			b.WriteString("jellyfin:\n")
			b.WriteString("  url: \"http://jellyfin:8096\"\n")
			b.WriteString("  api_key: ${MEDIAMATE_JELLYFIN_API_KEY}\n\n")
		}
	case ComponentPlex:
		if cfg.HasComponent(ComponentPlex) {
			b.WriteString("# Plex support requires implementation\n")
			b.WriteString("# plex:\n")
			b.WriteString("#   url: \"http://plex:32400\"\n")
			b.WriteString("#   token: ${PLEX_TOKEN}\n\n")
		}
	}
}

// renderConfigFooter writes the Telegram and app settings sections.
func renderConfigFooter(b *strings.Builder) {
	b.WriteString("telegram:\n")
	b.WriteString("  bot_token: ${MEDIAMATE_TELEGRAM_BOT_TOKEN}\n\n")

	b.WriteString("app:\n")
	b.WriteString("  log_level: \"info\"\n")
	b.WriteString("  data_dir: \"/app/data\"\n")
}
